namespace: "gpu"

autoscaling:
  enabled: true
  queueLength: 3
  minReplicaCount: 1
  maxReplicaCount: 3
  queueNameVars:
    - SD_MODEL_IDS
    - WHISPER_MODEL_IDS
    - EMBEDDING_MODEL_IDS
    - WAV2LIP_MODEL_IDS
    - U2NET_MODEL_IDS
    - DIS_MODEL_IDS
    - NEMO_ASR_MODEL_IDS
    - AUDIO_LDM_MODEL_IDS
    - BARK_MODEL_IDS
    - SEAMLESS_MODEL_IDS
    - MMS_MODEL_IDS
    - SADTALKER_MODEL_IDS
    - DEFORUM_MODEL_IDS
    - GFPGAN_MODEL_IDS
    - ESRGAN_MODEL_IDS
    - LLM_MODEL_IDS

controlnetModelIds: &controlnetModelIds |-
    lllyasviel/sd-controlnet-canny
    lllyasviel/sd-controlnet-depth
    lllyasviel/sd-controlnet-hed
    lllyasviel/sd-controlnet-mlsd
    lllyasviel/sd-controlnet-normal
    lllyasviel/sd-controlnet-openpose
    lllyasviel/sd-controlnet-scribble
    lllyasviel/sd-controlnet-seg
    lllyasviel/control_v11f1e_sd15_tile
    ioclab/control_v1p_sd15_brightness
    monster-labs/control_v1p_sd15_qrcode_monster/v2

commonImgOld: &commonImgOld "crgooeyprodwestus1.azurecr.io/gooey-gpu-common:3"
commonImg: &commonImg "crgooeyprodwestus1.azurecr.io/gooey-gpu-common:8"
retroImg: &retroImg "crgooeyprodwestus1.azurecr.io/gooey-gpu-retro:6"
deforumImg: &deforumImg "crgooeyprodwestus1.azurecr.io/gooey-gpu-deforum_sd:1"

deployments:
  - name: "common-diffusion-dreamshaper"
    image: *commonImgOld
    limits:
      memory: "35Gi"
    env:
      IMPORTS: |-
        common.diffusion
        common.controlnet
      CONTROLNET_MODEL_IDS: *controlnetModelIds
      SD_MODEL_IDS: |-
        Lykon/DreamShaper
  - name: "common-diffusion-stable-diffusion-2-1"
    image: *commonImgOld
    limits:
      memory: "35Gi"
    env:
      IMPORTS: |-
        common.diffusion
        common.controlnet
      CONTROLNET_MODEL_IDS: *controlnetModelIds
      SD_MODEL_IDS: |-
        stabilityai/stable-diffusion-2-1
  - name: "common-diffusion-dreamlike-photoreal-2"
    image: *commonImgOld
    limits:
      memory: "35Gi"
    env:
      IMPORTS: |-
        common.diffusion
        common.controlnet
      CONTROLNET_MODEL_IDS: *controlnetModelIds
      SD_MODEL_IDS: |-
        dreamlike-art/dreamlike-photoreal-2.0
  - name: "common-diffusion-stable-diffusion-v1-5"
    image: *commonImgOld
    limits:
      memory: "35Gi"
    env:
      IMPORTS: |-
        common.diffusion
        common.controlnet
      CONTROLNET_MODEL_IDS: *controlnetModelIds
      SD_MODEL_IDS: |-
        runwayml/stable-diffusion-v1-5

  - name: "common-diffusion-on-demand"
    image: *commonImgOld
    autoscaling:
      minReplicaCount: 0
    limits:
      memory: "50Gi"
    env:
      IMPORTS: |-
        common.diffusion
        common.controlnet
      CONTROLNET_MODEL_IDS: *controlnetModelIds
      SD_MODEL_IDS: |-
        wavymulder/Analog-Diffusion
        prompthero/openjourney
        prompthero/openjourney-v2
        darkstorm2150/Protogen_v5.3_Official_Release

  - name: "common-diffusion-inpaint"
    image: *commonImgOld
    limits:
      memory: "20Gi"
    env:
      IMPORTS: |-
        common.diffusion
      CONTROLNET_MODEL_IDS: *controlnetModelIds
      SD_MODEL_IDS: |-
        stabilityai/stable-diffusion-2-inpainting
        runwayml/stable-diffusion-inpainting

  - name: "deforum-sd-1"
    image: *deforumImg
    autoscaling:
      queueLength: 2
      minReplicaCount: 2
      maxReplicaCount: 12
    limits:
      memory: "20Gi"
    env:
      IMPORTS: |-
        deforum_sd
      DEFORUM_MODEL_IDS: |-
        Protogen_V2.2.ckpt

  - name: "deforum-sd-epicdream"
    image: *deforumImg
    autoscaling:
      queueLength: 2
      minReplicaCount: 1
      maxReplicaCount: 3
    limits:
      memory: "20Gi"
    env:
      IMPORTS: |-
        deforum_sd
      DEFORUM_MODEL_IDS: |-
        epicdream.safetensors

  - name: "common-whisper-en-short"
    image: *commonImgOld
    limits:
      memory: "20Gi"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        openai/whisper-large-v2

  - name: "common-whisper-te-short"
    image: *commonImgOld
    autoscaling:
      minReplicaCount: 0
    limits:
      memory: "20Gi"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-telugu-large-v2

  - name: "common-whisper-en-te-long"
    image: *commonImgOld
    autoscaling:
      minReplicaCount: 0
    limits:
      memory: "40Gi"
    env:
      QUEUE_PREFIX: "gooey-gpu/long"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        openai/whisper-large-v2
        vasista22/whisper-telugu-large-v2

  - name: "common-whisper-hi-bho-short"
    image: *commonImgOld
    autoscaling:
      minReplicaCount: 0
    limits:
      memory: "10Gi"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-hindi-large-v2
        Harveenchadha/vakyansh-wav2vec2-bhojpuri-bhom-60

  - name: "common-whisper-hi-bho-long"
    image: *commonImgOld
    autoscaling:
      minReplicaCount: 0
    limits:
      memory: "40Gi"
    env:
      QUEUE_PREFIX: "gooey-gpu/long"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-hindi-large-v2
        Harveenchadha/vakyansh-wav2vec2-bhojpuri-bhom-60

  - name: "retro-nemo-asr"
    image: *retroImg
    autoscaling:
      minReplicaCount: 0
    limits:
      memory: "20Gi"
    env:
      IMPORTS: |-
          retro.nvidia_nemo
      NEMO_ASR_MODEL_IDS: |-
          https://objectstore.e2enetworks.net/indic-asr-public/checkpoints/conformer/english_large_data_fixed.nemo
          https://objectstore.e2enetworks.net/indic-asr-public/checkpoints/conformer/stt_hi_conformer_ctc_large_v2.nemo

  - name: "common-audio-ldm-bark"
    image: *commonImgOld
    autoscaling:
      minReplicaCount: 0
    limits:
      memory: "20Gi"
    env:
      IMPORTS: |-
        common.audio_ldm
        common.suno_ai_bark
      AUDIO_LDM_MODEL_IDS: |-
        cvssp/audioldm
      # BARK_MODEL_IDS env var is unused in code but here to
      # note that bark queue is loaded by suno_ai_bark module
      BARK_MODEL_IDS: |-
        bark

  - name: "common-seamless"
    image: *commonImg
    limits_gpu: "10Gi"
    limits:
      memory: "28Gi"  # (220 / 80) * 10
    env:
      IMPORTS: |-
        common.seamless_asr
      SEAMLESS_MODEL_IDS: |-
        facebook/seamless-m4t-v2-large

  - name: "common-diffusion-instruct-pix2pix"
    image: *commonImgOld
    limits:
      memory: "12Gi"
    env:
      IMPORTS: |-
        common.diffusion
      SD_MODEL_IDS: |-
        timbrooks/instruct-pix2pix

  - name: "common-diffusion-upscale"
    image: *commonImgOld
    limits:
      memory: "52Gi"
    env:
      IMPORTS: |-
        common.diffusion
      SD_MODEL_IDS: |-
        stabilityai/stable-diffusion-x4-upscaler

  - name: "common-mms"
    image: *commonImgOld
    limits:
      memory: "25Gi"
    env:
      IMPORTS: |-
        common.mms
      MMS_MODEL_IDS: |-
        facebook/mms-1b-all

  - name: "common-embeddings-1"
    image: *commonImgOld
    autoscaling:
      queueLength: 20
    limits:
      memory: "18Gi"
    env:
      IMPORTS: |-
        common.embeddings
      EMBEDDING_MODEL_IDS: |-
        intfloat/e5-large-v2
        intfloat/e5-base-v2
        intfloat/multilingual-e5-base
        intfloat/multilingual-e5-large
        thenlper/gte-large
        thenlper/gte-base

  - name: "retro-sadtalker"
    image: "crgooeyprodwestus1.azurecr.io/gooey-gpu-retro:14"
    autoscaling:
      queueLength: 2
      minReplicaCount: 3
      maxReplicaCount: 10
    limits_gpu: "8Gi"
    limits:
      memory: "25Gi" # (220 / 80) * 8
    env:
      IMPORTS: |-
        retro.sadtalker
      SADTALKER_MODEL_IDS: |-
        SadTalker_V0.0.2_512.safetensors

  - name: "retro-wav2lip-gan"
    image: "crgooeyprodwestus1.azurecr.io/gooey-gpu-retro:14"
    autoscaling:
      minReplicaCount: 2
      maxReplicaCount: 10
    limits_gpu: "10Gi"
    limits:
      memory: "30Gi" # (220 / 80) * 10
    env:
      IMPORTS: |-
        retro.wav2lip
      WAV2LIP_MODEL_IDS: |-
        wav2lip_gan.pth

  - name: "retro-u2net-dis"
    image: *retroImg
    autoscaling:
      queueLength: 20
    limits:
      memory: "9Gi"
    env:
      IMPORTS: |-
        retro.u2net
        retro.dis
      U2NET_MODEL_IDS: |-
        u2net
      DIS_MODEL_IDS: |-
        isnet-general-use.pth

  - name: "retro-gfpgan-esrgan"
    image: "crgooeyprodwestus1.azurecr.io/gooey-gpu-retro:8"
    autoscaling:
      queueLength: 2
      minReplicaCount: 1
      maxReplicaCount: 10
    limits:
      memory: "24Gi"
    env:
      IMPORTS: |-
        retro.gfpgan
      GFPGAN_MODEL_IDS: |-
        GFPGANv1.4
      ESRGAN_MODEL_IDS: |-
        RealESRGAN_x2plus

  - name: "common-llms-sealion-v2-1"
    image: *commonImg
    limits_gpu: "30Gi"
    limits:
      memory: "80Gi"  # (220 / 80) * 30
    env:
      IMPORTS: |-
        common.llms
      LLM_MODEL_IDS: |-
        aisingapore/llama3-8b-cpt-sea-lionv2.1-instruct

## Dependencies
nfs-server-provisioner:
  enabled: true

  nodeSelector:
    gpuEnabled: "false"

  persistence:
    enabled: true
    storageClass: "managed-csi-premium"
    size: 250Gi

  storageClass:
    defaultClass: true
    name: "nfs-1"
