autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

rabbitmqAutoscaling:
  enabled: true
  deployments:
    - name: "common-diffusion-4"
      queueName: "gooey-gpu/timbrooks/instruct-pix2pix"
      queueLength: "2"
      minReplicaCount: 1
      maxReplicaCount: 4
    - name: "deforum-sd-1"
      queueName: "gooey-gpu/Protogen_V2.2.ckpt"
      queueLength: "2"  # tasks per replica
      minReplicaCount: 2
      maxReplicaCount: 12
    - name: "deforum-sd-epicdream"
      queueName: "gooey-gpu/epicdream.safetensors"
      queueLength: "2"
      minReplicaCount: 0
      maxReplicaCount: 1
    - name: "common-audio-ldm-bark"
      queueName: "gooey-gpu/cvssp/audioldm"
      queueLength: "2"
      minReplicaCount: 0
      maxReplicaCount: 1

persistence:
  enabled: true
  storageClass: "premium-rwo"
  size: 250Gi

storageClass:
  defaultClass: true

commonImg: &commonImg "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/common@sha256:43ce3db1869b8eb151989270a7dfe4f9a68ee887fa5d86ca0d238e185b4e96c1"
retroImg: &retroImg "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/retro@sha256:16b0cd846bff171b2a087f6409658c08748bbdf7e308474820c7a6e96eef8695"
deforumImg: &deforumImg "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu-dev/deforum_sd@sha256:fefdf0b01f6894aa6943c5afe7022b44e109f64c241512ca268b7d173d985a01"

controlnetModelIds: &controlnetModelIds |-
    lllyasviel/sd-controlnet-canny
    lllyasviel/sd-controlnet-depth
    lllyasviel/sd-controlnet-hed
    lllyasviel/sd-controlnet-mlsd
    lllyasviel/sd-controlnet-normal
    lllyasviel/sd-controlnet-openpose
    lllyasviel/sd-controlnet-scribble
    lllyasviel/sd-controlnet-seg
    lllyasviel/control_v11f1e_sd15_tile
    ioclab/control_v1p_sd15_brightness
    monster-labs/control_v1p_sd15_qrcode_monster/v2

deployments:
  - name: "common-diffusion-new"
    image: *commonImg
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "75Gi"
      cpu: "10"
    env:
      IMPORTS: |-
        common.diffusion
        common.controlnet
      CONTROLNET_MODEL_IDS: *controlnetModelIds
      SD_MODEL_IDS: |-
        runwayml/stable-diffusion-v1-5
        stabilityai/stable-diffusion-2-1
        Lykon/DreamShaper
        wavymulder/Analog-Diffusion
        prompthero/openjourney
        prompthero/openjourney-v2
        dreamlike-art/dreamlike-photoreal-2.0
        darkstorm2150/Protogen_v5.3_Official_Release

  - name: "common-diffusion-inpaint"
    image: *commonImg
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
        common.diffusion
      CONTROLNET_MODEL_IDS: *controlnetModelIds
      SD_MODEL_IDS: |-
        stabilityai/stable-diffusion-2-inpainting
        runwayml/stable-diffusion-inpainting

  - name: "common-diffusion-4"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
        common.diffusion
      SD_MODEL_IDS: |-
        timbrooks/instruct-pix2pix
  - name: "common-diffusion-upscale"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      memory: "12Gi"
      cpu: "3"
    env:
      IMPORTS: |-
        common.diffusion
      SD_MODEL_IDS: |-
        stabilityai/stable-diffusion-x4-upscaler

  - name: "deforum-sd-1"
    image: *deforumImg
    replicas: 2
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
        deforum_sd
      MODEL_IDS: |-
        Protogen_V2.2.ckpt

  - name: "deforum-sd-epicdream"
    image: *deforumImg
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
        deforum_sd
      MODEL_IDS: |-
        epicdream.safetensors

  - name: "common-whisper-short"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        openai/whisper-large-v2
  - name: "common-whisper-short-telugu"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-telugu-large-v2
  - name: "common-whisper-short-hindi"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-hindi-large-v2
  - name: "common-asr-short"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        Harveenchadha/vakyansh-wav2vec2-bhojpuri-bhom-60

  - name: "common-whisper-long"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      memory: "12Gi"
      cpu: "3"
    env:
      QUEUE_PREFIX: "gooey-gpu/long"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        openai/whisper-large-v2
        Harveenchadha/vakyansh-wav2vec2-bhojpuri-bhom-60

  - name: "common-whisper-long-indic"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      memory: "12Gi"
      cpu: "3"
    env:
      QUEUE_PREFIX: "gooey-gpu/long"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-telugu-large-v2
        vasista22/whisper-hindi-large-v2

  - name: "common-embeddings-1"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    limits:
      memory: "10Gi"
      cpu: "15"
    env:
      IMPORTS: |-
        common.embeddings
      EMBEDDING_MODEL_IDS: |-
        intfloat/e5-large-v2
        intfloat/e5-base-v2
        intfloat/multilingual-e5-base
        intfloat/multilingual-e5-large
        thenlper/gte-large
        thenlper/gte-base

  - name: "retro-wav2lip-gan"
    image: *retroImg
    replicas: 3
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    limits:
      memory: "10Gi"
      cpu: "15"
    env:
      IMPORTS: |-
        retro.wav2lip
      WAV2LIP_MODEL_IDS: |-
        wav2lip_gan.pth

  - name: "retro-u2net-dis"
    image: *retroImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    limits:
      memory: "10Gi"
      cpu: "15"
    env:
      IMPORTS: |-
          retro.u2net
          retro.dis
      U2NET_MODEL_IDS: |-
          u2net
      DIS_MODEL_IDS: |-
          isnet-general-use.pth

  - name: "retro-nemo-asr"
    image: *retroImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
          retro.nvidia_nemo
      NEMO_ASR_MODEL_IDS: |-
          https://objectstore.e2enetworks.net/indic-asr-public/checkpoints/conformer/english_large_data_fixed.nemo
          https://objectstore.e2enetworks.net/indic-asr-public/checkpoints/conformer/stt_hi_conformer_ctc_large_v2.nemo

  - name: "common-audio-ldm-bark"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
        common.audio_ldm
        common.suno_ai_bark
      AUDIO_LDM_MODEL_IDS: |-
        cvssp/audioldm
