autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

rabbitmqAutoscaling:
  enabled: true
  queueNameVars:
    - MODEL_IDS
    - SD_MODEL_IDS
    - WHISPER_MODEL_IDS
    - EMBEDDING_MODEL_IDS
    - WAV2LIP_MODEL_IDS
    - U2NET_MODEL_IDS
    - DIS_MODEL_IDS
    - NEMO_ASR_MODEL_IDS
    - AUDIO_LDM_MODEL_IDS
    - BARK_MODEL_IDS
    - SEAMLESS_MODEL_IDS
  defaultQueueLength: "2"

commonImg: &commonImg "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/common@sha256:43ce3db1869b8eb151989270a7dfe4f9a68ee887fa5d86ca0d238e185b4e96c1"
retroImg: &retroImg "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/retro@sha256:85053077c29f4a3f4edc724924f4bebf736402872810ee3d6d430272430b6032"

deployments: []

nfs-server-provisioner:
  # already deployed with nfs-server chart name in GCP
  #
  enabled: false

  persistence:
    enabled: true
    storageClass: "premium-rwo"
    size: 250Gi

  storageClass:
    defaultClass: true
