autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

persistence:
  enabled: true
  storageClass: "premium-rwo"
  size: 250Gi

storageClass:
  defaultClass: true

commonImg: &commonImg "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/common@sha256:a1bc2859bd912def52cb52ae48dd3be4fedbdec712d47914ed783d81c20577cd"
retroImg: &retroImg "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/retro@sha256:ac899280f686064ea192edf96c8ff7eef627900ac124f8a595463e1a622234ba"
deforumImg: &deforumImg "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu-dev/deforum_sd@sha256:fefdf0b01f6894aa6943c5afe7022b44e109f64c241512ca268b7d173d985a01"

controlnetModelIds: &controlnetModelIds |-
    lllyasviel/sd-controlnet-canny
    lllyasviel/sd-controlnet-depth
    lllyasviel/sd-controlnet-hed
    lllyasviel/sd-controlnet-mlsd
    lllyasviel/sd-controlnet-normal
    lllyasviel/sd-controlnet-openpose
    lllyasviel/sd-controlnet-scribble
    lllyasviel/sd-controlnet-seg
    lllyasviel/control_v11f1e_sd15_tile
    ioclab/control_v1p_sd15_brightness
    monster-labs/control_v1p_sd15_qrcode_monster/v2

deployments:
  - name: "common-diffusion-new"
    image: *commonImg
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "75Gi"
      cpu: "10"
    env:
      IMPORTS: |-
        common.diffusion
        common.controlnet
      CONTROLNET_MODEL_IDS: *controlnetModelIds
      SD_MODEL_IDS: |-
        runwayml/stable-diffusion-v1-5
        stabilityai/stable-diffusion-2-1
        Lykon/DreamShaper
        wavymulder/Analog-Diffusion
        prompthero/openjourney
        prompthero/openjourney-v2
        dreamlike-art/dreamlike-photoreal-2.0
        devxpy/rodent-diffusion-1-5
        darkstorm2150/Protogen_v5.3_Official_Release

#  - name: "common-diffusion-dreamlike-photoreal"
#    image: "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/common@sha256:6903d8c0220f78236e1d285f595464c826c9c3bffbeecde70c380c733be428b7"
#    nodeSelector:
#      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
#      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
#    limits:
#      memory: "15Gi"
#      cpu: "1"
#    env:
#      IMPORTS: |-
#        common.diffusion
#        common.controlnet
#      CONTROLNET_MODEL_IDS: *controlnetModelIds
#      SD_MODEL_IDS: |-
#        dreamlike-art/dreamlike-photoreal-2.0
#  - name: "common-diffusion-wuerstchen"
#    image: "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/common@sha256:c4b5872a9b658e27023d3a2410282763d688859d31efd5b2ce1ed3ca1a60c605"
#    nodeSelector:
#      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
#      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
#    limits:
#      memory: "15Gi"
#      cpu: "1"
#    env:
#      IMPORTS: |-
#        common.diffusion
#        common.controlnet
#      CONTROLNET_MODEL_IDS: *controlnetModelIds
#      SD_MODEL_IDS: |-
#        warp-ai/wuerstchen

  - name: "common-diffusion-4"
    image: *commonImg
    replicas: 4
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
        common.diffusion
      SD_MODEL_IDS: |-
        timbrooks/instruct-pix2pix
  - name: "common-diffusion-upscale"
    image: *commonImg
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      memory: "12Gi"
      cpu: "3"
    env:
      IMPORTS: |-
        common.diffusion
      SD_MODEL_IDS: |-
        stabilityai/stable-diffusion-x4-upscaler

  - name: "deforum-sd-1"
    image: *deforumImg
    replicas: 12
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
        deforum_sd
      MODEL_IDS: |-
        Protogen_V2.2.ckpt

  - name: "deforum-sd-epicdream"
    image: *deforumImg
    replicas: 2
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
        deforum_sd
      MODEL_IDS: |-
        epicdream.safetensors

  - name: "common-whisper-short"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        openai/whisper-large-v2
  - name: "common-whisper-short-telugu"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-telugu-large-v2
  - name: "common-whisper-short-hindi"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-hindi-large-v2
  - name: "common-asr-short"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        Harveenchadha/vakyansh-wav2vec2-bhojpuri-bhom-60

  - name: "common-whisper-long"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      memory: "12Gi"
      cpu: "3"
    env:
      QUEUE_PREFIX: "gooey-gpu/long"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        openai/whisper-large-v2
        Harveenchadha/vakyansh-wav2vec2-bhojpuri-bhom-60

  - name: "common-whisper-long-indic"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      memory: "12Gi"
      cpu: "3"
    env:
      QUEUE_PREFIX: "gooey-gpu/long"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-telugu-large-v2
        vasista22/whisper-hindi-large-v2

  - name: "common-embeddings-1"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    limits:
      memory: "10Gi"
      cpu: "15"
    env:
      IMPORTS: |-
        common.embeddings
      EMBEDDING_MODEL_IDS: |-
        intfloat/e5-large-v2
        intfloat/e5-base-v2
        intfloat/multilingual-e5-base
        intfloat/multilingual-e5-large
        thenlper/gte-large
        thenlper/gte-base

  - name: "retro-wav2lip-gan"
    image: *retroImg
    replicas: 3
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    limits:
      memory: "10Gi"
      cpu: "15"
    env:
      IMPORTS: |-
        retro.wav2lip
      WAV2LIP_MODEL_IDS: |-
        wav2lip_gan.pth

  - name: "retro-u2net-dis"
    image: "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/retro@sha256:bed82b71fe4d524f43de25e04c59a185d909c6bb5cb01ddb66079652867d74d8"
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    limits:
      memory: "10Gi"
      cpu: "15"
    env:
      IMPORTS: |-
          retro.u2net
          retro.dis
      U2NET_MODEL_IDS: |-
          u2net
      DIS_MODEL_IDS: |-
          isnet-general-use.pth

  - name: "retro-nemo-asr"
    image: "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/retro@sha256:bed82b71fe4d524f43de25e04c59a185d909c6bb5cb01ddb66079652867d74d8"
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
          retro.nvidia_nemo
      NEMO_ASR_MODEL_IDS: |-
          https://objectstore.e2enetworks.net/indic-asr-public/checkpoints/conformer/english_large_data_fixed.nemo
          https://objectstore.e2enetworks.net/indic-asr-public/checkpoints/conformer/stt_hi_conformer_ctc_large_v2.nemo

  - name: "common-audio-ldm-bark"
    image: "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/common@sha256:22485dcda2560bffd1b863d9779421dca1012bc966a47aa2a120205820a85683"
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
      cloud.google.com/gke-max-shared-clients-per-gpu: "5"
    limits:
      memory: "15Gi"
      cpu: "1"
    env:
      IMPORTS: |-
        common.audio_ldm
        common.suno_ai_bark
      AUDIO_LDM_MODEL_IDS: |-
          cvssp/audioldm
