autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

rabbitmqAutoscaling:
  enabled: true
  deployments:
    - name: "common-diffusion-instruct-pix2pix"
      queueName: "gooey-gpu/timbrooks/instruct-pix2pix"
      queueLength: "2"
      minReplicaCount: 1
      maxReplicaCount: 4
    - name: "retro-wav2lip-gan"
      queueName: "gooey-gpu/retro/wav2lip_gan.pth"
      queueLength: "2"
      minReplicaCount: 3
      maxReplicaCount: 12

commonImg: &commonImg "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/common@sha256:43ce3db1869b8eb151989270a7dfe4f9a68ee887fa5d86ca0d238e185b4e96c1"
retroImg: &retroImg "us-docker.pkg.dev/dara-c1b52/cloudbuild/gooey-gpu/retro@sha256:85053077c29f4a3f4edc724924f4bebf736402872810ee3d6d430272430b6032"

## not deployed here
#
# common-diffusion-new
# common-diffusion-on-demand
# common-diffusion-inpaint
# deforum-sd-1
# deforum-sd-epicdream
# common-whisper-en-short
# common-whisper-te-short
# retro-nemo-asr
# common-audio-ldm-bark
# common-seamless

deployments:
  - name: "common-diffusion-instruct-pix2pix"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      nvidia.com/gpu: "1"
      memory: "12Gi"
      cpu: "3"
    env:
      IMPORTS: |-
        common.diffusion
      SD_MODEL_IDS: |-
        timbrooks/instruct-pix2pix
  - name: "common-diffusion-upscale"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      nvidia.com/gpu: "1"
      memory: "12Gi"
      cpu: "3"
    env:
      IMPORTS: |-
        common.diffusion
      SD_MODEL_IDS: |-
        stabilityai/stable-diffusion-x4-upscaler

  - name: "common-whisper-en-te-long"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      nvidia.com/gpu: "1"
      memory: "12Gi"
      cpu: "3"
    env:
      QUEUE_PREFIX: "gooey-gpu/long"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        openai/whisper-large-v2
        vasista22/whisper-telugu-large-v2
  - name: "common-whisper-hi-bho-long"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      nvidia.com/gpu: "1"
      memory: "12Gi"
      cpu: "3"
    env:
      QUEUE_PREFIX: "gooey-gpu/long"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-hindi-large-v2
        Harveenchadha/vakyansh-wav2vec2-bhojpuri-bhom-60
  - name: "common-whisper-hi-bho-short"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-l4"
    limits:
      nvidia.com/gpu: "1"
      memory: "12Gi"
      cpu: "3"
    env:
      QUEUE_PREFIX: "gooey-gpu/short"
      IMPORTS: |-
        common.whisper
      WHISPER_MODEL_IDS: |-
        vasista22/whisper-hindi-large-v2
        Harveenchadha/vakyansh-wav2vec2-bhojpuri-bhom-60

  - name: "common-embeddings-1"
    image: *commonImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    limits:
      nvidia.com/gpu: "1"
      memory: "10Gi"
      cpu: "15"
    env:
      IMPORTS: |-
        common.embeddings
      EMBEDDING_MODEL_IDS: |-
        intfloat/e5-large-v2
        intfloat/e5-base-v2
        intfloat/multilingual-e5-base
        intfloat/multilingual-e5-large
        thenlper/gte-large
        thenlper/gte-base

  - name: "retro-wav2lip-gan"
    image: *retroImg
    replicas: 3
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    limits:
      nvidia.com/gpu: "1"
      memory: "10Gi"
      cpu: "15"
    env:
      IMPORTS: |-
        retro.wav2lip
      WAV2LIP_MODEL_IDS: |-
        wav2lip_gan.pth

  - name: "retro-u2net-dis"
    image: *retroImg
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    limits:
      nvidia.com/gpu: "1"
      memory: "10Gi"
      cpu: "15"
    env:
      IMPORTS: |-
          retro.u2net
          retro.dis
      U2NET_MODEL_IDS: |-
          u2net
      DIS_MODEL_IDS: |-
          isnet-general-use.pth

nfs-server-provisioner:
  # already deployed with nfs-server chart name in GCP
  #
  enabled: false

  persistence:
    enabled: true
    storageClass: "premium-rwo"
    size: 250Gi

  storageClass:
    defaultClass: true
