commonEnv:
  BROKER_URL: "amqp://username:password@service-name.svc.cluster.local:5672"
  RESULT_BACKEND: "redis://:password@host"
  SENTRY_DSN: "XXXX"
  HUGGING_FACE_HUB_TOKEN: "hf_XXXX"

namespace: "default"

redis:
  service:
    type: "LoadBalancer"
    loadBalancerIP: "XX.XX.XX.XX"
    loadBalancerSourceRanges:
    - "XX.XX.XX.XX/32"

rabbitmq:
  service:
    type: "LoadBalancer"
    loadBalancerIP: "XX.XX.XX.XX"
    loadBalancerSourceRanges:
    - "XX.XX.XX.XX/32"
