commonEnv:
  BROKER_URL: "amqp://username:password@<svc-name>:5672"
  CLUSTER_WIDE_BROKER_URL: "amqp://username:password@<svc-name>.<namespace>.svc.cluster.local:5672"
  RESULT_BACKEND: "redis://:password@host"
  SENTRY_DSN: "XXXX"
  HUGGING_FACE_HUB_TOKEN: "hf_XXXX"
