---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ $.Release.Name }}-pvc"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
