{{- if .Values.rabbitmqAutoscaling.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: "{{ $.Values.namespace }}"
spec:
  env:
    - parameter: host
      name: BROKER_URL
{{- end }}

{{- range .Values.rabbitmqAutoscaling.deployments }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{{ $.Release.Name }}-rabbitmq-{{ .name }}"
  namespace: "{{ $.Values.namespace }}"
spec:
  scaleTargetRef:
    name: "{{ $.Release.Name }}-{{ .name }}"
  minReplicaCount: {{ .minReplicaCount }}
  maxReplicaCount: {{ .maxReplicaCount }}
  pollingInterval: {{ .pollingInterval | default 3 }}
  cooldownPeriod: {{ .cooldownPeriod | default 1200 }}
  triggers:
    {{- if .queueNames }}
    {{- $queueLength := .queueLength }}
    {{- range .queueNames }}
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: "{{ .}}"
        mode: QueueLength
        value: "{{ $queueLength }}"
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn
    {{- end }}
    {{- else }}
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: "{{ .queueName }}"
        mode: QueueLength
        value: "{{ .queueLength }}"
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn
    {{- end }}
{{- end }}
