{{- if .Values.rabbitmqAutoscaling.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: "{{ $.Values.namespace }}"
spec:
  env:
    - parameter: host
      name: BROKER_URL
{{- end }}

{{- if .Values.rabbitmqAutoscaling.enabled }}
{{- range $deployment := .Values.deployments }}
{{- $overrides := get $.Values.rabbitmqAutoscaling.overrides .name | default (dict) }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{{ $.Release.Name }}-rabbitmq-{{ .name }}"
  namespace: "{{ $.Values.namespace }}"
spec:
  scaleTargetRef:
    name: "{{ $.Release.Name }}-{{ .name }}"
  {{- $minReplicaCount := $overrides.minReplicaCount | default $deployment.replicas }}
  minReplicaCount: {{ $minReplicaCount }}
  maxReplicaCount: {{ $overrides.maxReplicaCount | default (add $minReplicaCount 2) }}
  pollingInterval: 3
  cooldownPeriod: 1200
  triggers:
    {{- if $overrides.queueNames }}
    {{- range $queueName := $overrides.queueNames }}
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: "{{ $queueName }}"
        mode: QueueLength
        value: "{{ $overrides.queueLength | default $.Values.rabbitmqAutoscaling.defaultQueueLength }}"
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn
    {{- end }}
    {{- else }}
    {{- $queuePrefix := get $deployment.env "QUEUE_PREFIX" | default "gooey-gpu" }}
    {{- range $queueNameVar := $.Values.rabbitmqAutoscaling.queueNameVars }}
    {{- range $queue := regexSplit "\n" (get $deployment.env $queueNameVar | default "") -1 | compact }}
    {{- $queueName := printf "%s/%s" $queuePrefix $queue }}
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: "{{ $queueName }}"
        mode: QueueLength
        value: "{{ $overrides.queueLength | default $.Values.rabbitmqAutoscaling.defaultQueueLength }}"
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
