apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ilb-svc
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/component: rabbitmq-server
    app.kubernetes.io/name: rabbitmq-1
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  # $ gcloud compute addresses create redis-ilb-svc --project=dara-c1b52 --description=Redis\ internal\ IP --region=us-central1 --subnet=default --purpose=GCE_ENDPOINT
  # $ gcloud compute addresses describe redis-ilb-svc --region us-central1
  loadBalancerIP: 10.128.0.49
---
apiVersion: v1
kind: Service
metadata:
  name: redis-ilb-svc
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: redis-ha-haproxy
    app.kubernetes.io/name: redis-ha-1
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  # $ gcloud compute addresses create rabbitmq-ilb-svc --project=dara-c1b52 --description=RabbitMQ\ internal\ IP --region=us-central1 --subnet=default --purpose=GCE_ENDPOINT
  # $ gcloud compute addresses describe rabbitmq-ilb-svc --region us-central1
  loadBalancerIP: 10.128.0.39
