{{- range .Values.serviceMonitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ $.Release.Name }}-{{ .name }}"
  namespace: "{{ .namespace | default $.Release.Name }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .name }}"
  endpoints:
   - port: "{{ .port }}"
{{- end }}
