## Configuration for the kube-prometheus-stack subchart
##
kube-prometheus-stack:
  ## Override the deployment namespace
  ##
  namespaceOverride: "monitoring"

  prometheus:
    prometheusSpec:
      ## Scrape metrics from all service/pod monitors
      ## in the cluster with no filtering
      ##
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}

## Toggle switch for rabbitmq exporter subchart
##
rabbitmqExporter:
  enabled: true

## Configuration for rabbitmq exporter subchart
##
prometheus-rabbitmq-exporter:
  # namespace must be "gpu" because secrets (rabbitmq-password)
  # can't be shared between namespaces
  namespaceOverride: "gpu"

  prometheus:
    monitor:
      enabled: true
      namespace:
        - "gpu"

  rabbitmq:
    url: "http://rabbitmq.gpu.svc.cluster.local:15672"
    user: "user"
    existingPasswordSecret: "rabbitmq"
    existingPasswordSecretKey: "rabbitmq-password"
